---
AllCops:
  TargetRubyVersion: 2.5

require:
  - rubocop-rspec
  - rubocop-rails

Metrics/BlockLength:
  Exclude:
    - db/migrations/*
    - spec/**/*_spec.rb

RSpec/MessageSpies:
  EnforcedStyle: receive
