---
AllCops:
  TargetRubyVersion: 2.5

require:
  - rubocop-rspec
  - rubocop-rails

RSpec/MultipleExpectations:
  Exclude:
    - spec/**/*_spec.rb

Metrics/BlockLength:
  Exclude:
    - db/migrations/*
    - spec/**/*_spec.rb

RSpec/MessageSpies:
  EnforcedStyle: receive
