---
AllCops:
  TargetRubyVersion: 2.5

require:
  - rubocop-rspec
  - rubocop-rails

RSpec/MultipleExpectations:
  Exclude:
    - spec/**/*_spec.rb

Naming/RescuedExceptionsVariableName:
  Exclude:
    - app/controllers/application_controller/error_handler.rb

Metrics/BlockLength:
  Exclude:
    - db/migrate/*
    - spec/**/*_spec.rb

RSpec/MessageSpies:
  EnforcedStyle: receive
